#!/bin/bash
pytest --ignore=tests/integration/ --cov=ujt --cov-report= -vv -s
if [ -z "$CI" ]
then
    pytest tests/integration/ --cov=ujt -vv -s --cov-append --local
else
    pytest tests/integration/ --cov=ujt -vv -s --cov-append
fi
coverage report

