name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Compile protobufs
      run: |
        ./generate_protos
        pip install --editable generated/
    - name: Lint
      run: |
        pylint -E ujt tests
        autoflake -c -r --remove-all-unused-imports ujt tests 
        black --check ujt tests
    - name: Type checking
      run: |
        mypy ujt tests
    - name: Test
      run: |
        ./test
